### ISSUE TITLE
Inconsistent test results

### ISSUE THREAD

**Issue by jelhan** [rwjblue/ember-cli-content-security-policy#200]
The following test is expected to be broken for Ember CLI 3.26.1 due to #199 

https://github.com/rwjblue/ember-cli-content-security-policy/blob/93924fa54dd472de89ea0b0f5d1f126c40758c9a/node-tests/e2e/test-support-test.js#L69-L75

It is in-deed failing locally when executed using global `mocha`:

```
$ DEBUG=ember-addon-tests mocha node-tests/**/*-test.js --grep "tests are passing for untouched application"


  e2e: provides test support
  ember-addon-tests initalize workspace +0ms
  ember-addon-tests created workspace directory at /tmp/ember-addon-tests-ZNw1lm +1ms
  ember-addon-tests configured workspace +1ms
  ember-addon-tests Indentifying packages under test for package located at /home/main/Code/ember-ecosystem/ember-cli-content-security-policy +0ms
  ember-addon-tests Project does not use Yarn workspaces +194ms
  ember-addon-tests link package ember-cli-content-security-policy located at /home/main/Code/ember-ecosystem/ember-cli-content-security-policy into yarn workspace +1ms
  ember-addon-tests linked all packages under test into yarn workspace +26ms
  ember-addon-tests install dependencies of packages under test +0ms
  ember-addon-tests installed dependencies of packages under test +38s
  ember-addon-tests initalized workspace at /tmp/ember-addon-tests-ZNw1lm +0ms
  ember-addon-tests created test project at /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm +160ms
  ember-addon-tests execute command `ember new a8nOQZm --skip-git --yarn --directory /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm` in /home/main +3ms
  ember-addon-tests executed command `ember new a8nOQZm --skip-git --yarn --directory /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm` in /home/main +23s
  ember-addon-tests execute command `yarn install` in /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm +3ms
  ember-addon-tests executed command `yarn install` in /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm +5s
  ember-addon-tests execute command `yarn remove ember-auto-import` in /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm +0ms
  ember-addon-tests executed command `yarn remove ember-auto-import` in /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm +5s
    does not cause test failures on new project
  ember-addon-tests execute command `ember test` in /tmp/ember-addon-tests-ZNw1lm/test-projects/a8nOQZm +6ms
      1) tests are passing for untouched application


  0 passing (6m)
  1 failing

  1) e2e: provides test support
       does not cause test failures on new project
         tests are passing for untouched application:
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/main/Code/ember-ecosystem/ember-cli-content-security-policy/node-tests/e2e/test-support-test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

But it is passing, when using the `test:node` script included in `package.json`:

```
$ DEBUG=ember-addon-tests yarn test:node --grep "tests are passing for untouched application"
yarn run v1.22.5
$ mocha node-tests/**/*-test.js --grep 'tests are passing for untouched application'


  e2e: provides test support
  ember-addon-tests initalize workspace +0ms
  ember-addon-tests created workspace directory at /tmp/ember-addon-tests-5ZEM1N +0ms
  ember-addon-tests configured workspace +1ms
  ember-addon-tests Indentifying packages under test for package located at /home/main/Code/ember-ecosystem/ember-cli-content-security-policy +0ms
  ember-addon-tests Project does not use Yarn workspaces +193ms
  ember-addon-tests link package ember-cli-content-security-policy located at /home/main/Code/ember-ecosystem/ember-cli-content-security-policy into yarn workspace +0ms
  ember-addon-tests linked all packages under test into yarn workspace +25ms
  ember-addon-tests install dependencies of packages under test +1ms
  ember-addon-tests installed dependencies of packages under test +39s
  ember-addon-tests initalized workspace at /tmp/ember-addon-tests-5ZEM1N +0ms
  ember-addon-tests created test project at /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO +168ms
  ember-addon-tests execute command `ember new aiOuwwO --skip-git --yarn --directory /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO` in /home/main +3ms
  ember-addon-tests executed command `ember new aiOuwwO --skip-git --yarn --directory /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO` in /home/main +19s
  ember-addon-tests execute command `yarn install` in /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO +3ms
  ember-addon-tests executed command `yarn install` in /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO +5s
  ember-addon-tests execute command `yarn remove ember-auto-import` in /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO +0ms
  ember-addon-tests executed command `yarn remove ember-auto-import` in /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO +4s
    does not cause test failures on new project
  ember-addon-tests execute command `ember test` in /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO +5ms
  ember-addon-tests executed command `ember test` in /tmp/ember-addon-tests-5ZEM1N/test-projects/aiOuwwO +12s
      ✓ tests are passing for untouched application (11799ms)


  1 passing (1m)

Done in 79.96s.
```

This is _very_ confusing to me because the script is just an alias for the above command: :exploding_head: 

https://github.com/rwjblue/ember-cli-content-security-policy/blob/93924fa54dd472de89ea0b0f5d1f126c40758c9a/package.json#L25

I also verified that it is not an issue of global `mocha` versus locally installed `mocha`. Using `node_modules/.bin/mocha` is giving the same results as using global `mocha`. Both are failing as expected.

The CI pipeline uses `yarn test:node`: https://github.com/rwjblue/ember-cli-content-security-policy/blob/93924fa54dd472de89ea0b0f5d1f126c40758c9a/.github/workflows/ci.yml#L184 It might therefore give wrong results. :scream:

**Comment by jelhan** [comment]
From the [yarn documentation](https://classic.yarnpkg.com/en/docs/cli/run/#toc-yarn-run-script):

> `yarn run [script] [<args>]`
> 
> (...)
>
> `[script]` can also be any locally installed executable that is inside `node_modules/.bin/`.

It is even more explicit in [npm documentation](https://docs.npmjs.com/cli/v7/using-npm/scripts#path) for `scripts` in `package.json`:

> **path**
>
> If you depend on modules that define executable scripts, like test suites, then those executables will be added to the PATH for executing the scripts.

[ember-addon-tests](https://github.com/jelhan/ember-addon-tests), which is used for writing the tests, creates the projects to run the tests against by executing `ember` binary in a shell. If run via `scripts` in `package.json` the `ember` binary will always resolve to the one provided by `ember-cli` package installed in the project - regardless of current working directory. This explains the difference between executing the tests with `yarn test:node` or `mocha node-tests/**/*-test.js`.

#202 should fix it by executing the Ember CLI scenarios _without_ using the script provided in `package.json`.
